@[ if field.is_skip() ] /* nothing */
@[ elif field.is_object() ]
    @[ if field.is_array() ]
        @[ include "field/objarray.h" with context ]
    @[ else ]
        @[ include "field/object.h" with context ]
    @[ endif ]
@[ elif field.is_union() ]
    @[ include "field/inner.h" with context ]
@[ elif field.is_struct() ]
    @[ include "field/inner.h" with context ]
@[ elif field.enum == "bitmap" ]
    @[ include "field/bitmap.h" with context ]
@[ elif field.is_array() ]
    @[ if field.is_string_array() ]
        @[ include "field/strarray.h" with context ]
    @[ elif field.enum == "uuid" ]
        @[ include "field/bytearray.h" with context ]
    @[ elif field.is_pointer() ]
        @[ include "field/ptrarray.h" with context ]
    @[ elif field.is_cstr() ]
        @[ include "field/bytearray.h" with context ]
    @[ elif field.is_int() ]
        @[ include "field/intarray.h" with context ]
    @[ else ]
        #error "unsupported array type for field '@(field.name)'"
    @[ endif ]
@[ elif field.is_implicit() ]
    @[ if field.is_offset() ]
        @[ include "field/implicit/offset.h" with context ]
    @[ elif field.is_pointer() ]
        @[ include "field/implicit/pointer.h" with context ]
    @[ elif field.is_enum() and field.category.type != "flag" ]
        @[ include "field/implicit/enum.h" with context ] 
    @[ else ]
        @[ include "field/implicit/integer.h" with context ]
    @[ endif ]
@[ elif field.is_offset() ]
    @[ include "field/offset.h" with context ]    
@[ elif field.is_pointer() ]
    @[ include "field/pointer.h" with context ]
@[ elif field.is_enum() ]
    @[ if field.category.type == "flag" ]
        @[ include "field/bitfield.h" with context ]
    @[ else ] /* enum or partial */
        @[ include "field/enum.h" with context ]
    @[ endif ]
@[ elif field.is_int() ]
    @[ include "field/scalar.h" with context ]
@[ else ]
    #error "unsupported type for field '@(field.name)'"
@[ endif ]

