@[ if field.is_skip() ] /* nothing */
@[ elif field.is_object() ]
    @[ if field.is_array() ]
        @[ include "field/objarray.cc" with context ]
    @[ endif ]
    /* no function definition is needed if the scalar field is an object */
@[ elif field.is_union() ]
    @[ include "field/inner.cc" with context ]
@[ elif field.is_struct() ]
    @[ include "field/inner.cc" with context ]
@[ elif field.enum == "bitmap" ]
    @[ include "field/bitmap.cc" with context ]
@[ elif field.is_array() ]
    @[ if field.is_string_array() ]
        @[ include "field/strarray.cc" with context ]
    @[ elif field.enum == "uuid" ]
        @[ include "field/uuid.cc" with context ] 
    @[ elif field.is_pointer() ]
        @[ include "field/ptrarray.cc" with context ]
    @[ elif field.is_cstr() ]
        @[ include "field/cstring.cc" with context ]
    @[ elif field.is_int() ]
        @[ include "field/intarray.cc" with context ]
    @[ else ]
        #error "unsupported array type for field '@(field.name)'"
    @[ endif ]
@[ elif field.is_implicit() ]
    @[ if field.is_offset() ]
        @[ include "field/implicit/offset.cc" with context ]
    @[ elif field.is_pointer() ]
        @[ include "field/implicit/pointer.cc" with context ]
    @[ elif field.is_enum() and field.category.type != "flag" ]
        @[ include "field/implicit/enum.cc" with context ]
    @[ else ]
        @[ include "field/implicit/integer.cc" with context ]
    @[ endif ]
@[ elif field.is_offset() ]
    @[ include "field/offset.cc" with context ]        
@[ elif field.is_pointer() ]
    @[ include "field/pointer.cc" with context ]
@[ elif field.is_enum() ]
    @[ if field.category.type == "flag" ]
        @[ include "field/bitfield.cc" with context ]
    @[ else ] /* enum or partial */
        @[ include "field/enum.cc" with context ]
    @[ endif ]
@[ elif field.is_int() ]
    @[ include "field/scalar.cc" with context ]
@[ else ]
    #error "unsupported type for field '@(field.name)'"
@[ endif ]

